using consoleAppForStudents.SH;

/* 
    Reverse Engineering with EF Core: 
    - Generate C# classes from an existing database schema.
    - Let me use LINQ & C# to query/manipulate data.

    SchoolContext: 
    - My DbContext class (generated by EF Core). It manages the database connection and provides access to the database sets.

    context: 
    - An instance of the SchoolContext class, bridge my C# application and the database. 
*/

SchoolContext context = new();


/*

Create a console application that does the following:

1. Request the user to enter the name of a school, then list all the students in that school together with a count.
2. Display a count of students in each School 
3. Create a stored procedure for inserting data into the Student table.

*/